### PR TITLE
Simplify the gradle buildscript

### PR DESCRIPTION
**Pull request by zeichenreihe**
I'm cleaning up the gradle tasks:
- [x] Remove the task dependencies of `downloadCalamus` and `downloadCalamusV2` on `downloadMcJars`.
- [x] Add the graphviz graph of the task dependencies.
- [x] Remove the unnecessary output `.v1Output` of the `separateMappingsForBuild` task.

### CODE REVIEW

**Comment by SpaceWalkerRS** [comment]
As far as I know Tiny V1 is used for the sake of backwards compatibility. I could be wrong but I think the installer also bundles intermediary in Tiny V1 (though of course that doesn't mean Feather must still use it).

**Comment by johannes-schmatz** [comment]
I've seen some tasks that generate a Tiny V1 and all of the dependencies only us the Tiny V2 and the dependencies then call enigma to convert that one again... like this one:
https://github.com/OrnitheMC/feather-mappings/blob/e28cce1fb4853702bb8e9b68cdc5829a17a1a68e/build.gradle#L867-L871 the only use of it is with `separateMappingsForBuild.v2Output`...

**Comment by SpaceWalkerRS** [comment]
Hmm perhaps we can consider dropping Tiny V1 support then. Most, if not all, outside projects that depend on Feather mappings will use the Tiny V2 ones anyway.

**Comment by johannes-schmatz** [comment]
We can at least move Tiny v1 generation to be done from the generated Tiny v2 and not build itself... I'll push something that removes the (unused) conversion of the `separateMappingsForBuild` task. I don't know gradle well, I didn't test it, but it should be fine.

**Comment by SpaceWalkerRS** [comment]
good idea, that simplifies things a lot without removing that backwards compatibility

**Comment by zeichenreihe** [comment]
I added the graphviz graph showing the task dependencies.

**Comment by zeichenreihe** [comment]
I think this is a good point to split this PR up in two parts: one for the simple things and one for the more complex changes.

**Review by SpaceWalkerRS — APPROVED** [review]

**Pull request merged**
