### PR TITLE
Mapped some classses

### PR DESCRIPTION
**Pull request by 0marduk**
so i mapped some classes here and there

### CODE REVIEW

**Comment by SpaceWalkerRS** [comment]
I'll do a proper review later but there are some issues here, some yours and some our own. A few classes you mapped are anonymous classes and should be left unmapped. Some classes you mapped are Isom classes, which are mapped in later versions so you should check that out and make sure the names match. I'm afraid a lot of these issues happened because inner class patches are not yet applied for anything older than Beta.

**Comment by 0marduk** [comment]
Ohh damn, i previously thought that the compiler marked anonymous classes

**Comment by SpaceWalkerRS** [comment]
it's due to the obfuscation, the necessary attributes were removed from the bytecode, and we need to patch them back in

**Comment by 0marduk** [comment]
I see, is there a way to mark a class as anonymous?

**Comment by SpaceWalkerRS** [comment]
Not inside Enigma, no. We have inner class patches ready, we just need to apply them in Feather.

**Comment by 0marduk** [comment]
I see, this PR can be closed essentially

**Pull request closed without merging**
