### PR TITLE
Update CONVENTIONS.md

### PR DESCRIPTION
**Pull request by SpaceWalkerRS**
I have started making changes to the style guide as per issue #37. As these changes are still being discussed, this PR should be considered a DRAFT for the time being.

### CODE REVIEW

**Comment by viktor40** [comment]
I suggest changing:
`- Use `clazz` for class fields/parameters only if using the class' name is not applicable`
to:
`- Use `clazz` for class fields/parameters only if using the class' name is not applicable and if there is no class of which all possible values of the class parameter extend from`

I would also add something about using `posX`, `posY`, `posZ` only when clarification is needed (for example it might be beneficial when there are both chunk pos and block pos. Then the difference is more obvious but in other cases just use `x`, `y`, `z`.

**Comment by SpaceWalkerRS** [comment]
> I would also add something about using `posX`, `posY`, `posZ` only when clarification is needed

I would say that that is covered by the line
```
Coordinates can be named `x`, `y`, and `z` when it's clear what they represent.
```

**Review by KayleighWasTaken — COMMENTED** [review]
Looks good to me, can't really see any issues with the added content.

A couple things I forgot before that might be worth adding are `proxy` for `Proxy` and inherited fields, and `server` for `MinecraftServer` and inherited fields. You also forgot to mention to use `UPPER_SNAKE_CASE` for effectively final fields, but I don't actually remember the exact consensus we reached on that. Also we should probably mention what to do in cases where using the "normal" name for static finals isn't possible due to inheritance shenanigans (such as with `LOGGER`). Right now that is a mess of conventions being used.

**Comment by SpaceWalkerRS** [comment]
> Also we should probably mention what to do in cases where using the "normal" name for static finals isn't possible due to inheritance shenanigans (such as with `LOGGER`). Right now that is a mess of conventions being used.

This turned out to be an issue with Enigma, which was recently fixed.

**Review by Copetan — APPROVED** [review]

**Pull request merged**
