### PR TITLE
map StatusEfectStrings and PotionItem

### PR DESCRIPTION
**Pull request by EmiliaThorsen**
owo *throws instant damage 2 potion at you*

### CODE REVIEW

**Review by KayleighWasTaken — CHANGES_REQUESTED** [review]
Few changes that need to be made here.
- [ ] static final fields should be mapped with `UPPER_SNAKE_CASE` rather than `UpperCamelCase`.
- [ ] Some typos - `Cashe` => `Cache`, `Efect` => `Effect`, `Recipies` => `Recipes`.
- [ ] If you're changing `StatusEffectString` to `BrewingRecipeString` then update the javadocs for the relevant methods to match.
- [ ] `PointlessFlagRemap` doesn't seem like an appropriate name to me, please find a more descriptive name based off of what the remapped bits are used for.
- [ ] Avoid naming args things like `i`, `j`, `k`, give them more descriptive names based off what they are used for.
- [ ] Having `Int` in `CheckIntBit` feels a tad redundant to me, `CheckBit` might be more appropriate.
- [ ] Method names are supposed to be verbs, change `potionEffectMetadataUpdater` to something like `updatePotionEffectMetadata`

Not going to make this one an actual change request, but could you also explain the rationale behind the renaming of `StatusEffectString` to `BrewingRecipeString`?

**Comment by EmiliaThorsen** [comment]
fixed all the things you complained about, as for why it shouldn't be called statusefectstrings is because it has nothing to do with that lol, it has a few helper functions for updating potion metadata, getting potion sprite color, and the efects potions have, geting the name of the efects is done somewhere else.

**Review by KayleighWasTaken — CHANGES_REQUESTED** [review]
Typo in the first javadoc, `everyting` -> `everything`. You also didn't fix all the oddly named params, I'm seeing quite a few `j`, `bl`, etc. If you don't know what to call them its OK to leave them unmapped as well :heart:.

**Comment by EmiliaThorsen** [comment]
unmaped the bad mappes and fixed the typos, also clarified the weird function

**Review by KayleighWasTaken — APPROVED** [review]
OK I think this is good now.

**Review by Copetan — APPROVED** [review]

**Pull request merged**
